<h1>Torch Tensors in 1D</h1>
cf IBM courses.

<h2>Objective</h2><ul><li> How tensor operations work in pytorch.</li></ul> 
<h2>Preparation</h2>


In [1]:
# These are the libraries will be used for this lab.

import torch 
import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline  

<h2 id="Types_Shape">Types and Shape</h2>


You can create a tensor of integers <i>[0, 1, 2, 3, 4]</i> by applying the constructor <code>torch.tensor()</code>.
To do the same with float numbers replace the integers into floats and observe the new tensor type:

In [2]:
# Convert a integer list with length 5 to a tensor

ints_to_tensor = torch.tensor([0, 1, 2, 3, 4])
print("The type of tensor object after converting it to tensor: ", ints_to_tensor.type())

The type of tensor object after converting it to tensor:  torch.LongTensor


In [3]:
# Another method to convert the integer list to float tensor

old_int_tensor = torch.tensor([0, 1, 2, 3, 4, 5, 6])
new_float_tensor = old_int_tensor.type(torch.FloatTensor)
print("The type of the new_float_tensor:", new_float_tensor.type())

The type of the new_float_tensor: torch.FloatTensor


 <code><i>.size()</i></code> helps you to find out the size of the <code><i>tensor_obj</i></code>.
 
 <code><i>.ndimension()</i></code> shows the dimension of the tensor object.

In [4]:
# Introduce the tensor_obj.size() & tensor_ndimension.size() methods

print("\nThe size of the new_float_tensor: ", new_float_tensor.size())
print("\nThe dimension of the new_float_tensor: ",new_float_tensor.ndimension())


The size of the new_float_tensor:  torch.Size([7])

The dimension of the new_float_tensor:  1


You can also convert a <b>numpy</b> array to a <b>tensor</b> (as well as Pandas series, but not explained here), for example: 


In [5]:
# Convert a tensor to a numpy array

back_to_numpy = new_float_tensor.numpy()
print("The previous float tensor : ",new_float_tensor)
print("The numpy array from tensor: ", back_to_numpy)
print("The dtype of numpy array: ", type(back_to_numpy))

The previous float tensor :  tensor([0., 1., 2., 3., 4., 5., 6.])
The numpy array from tensor:  [0. 1. 2. 3. 4. 5. 6.]
The dtype of numpy array:  <class 'numpy.ndarray'>


we can use the method <code> tolist()</code> to return a list 


In [8]:
torch_to_list=new_float_tensor.tolist()

print('tensor:',new_float_tensor,"\nlist:",torch_to_list)

tensor: tensor([0., 1., 2., 3., 4., 5., 6.]) 
list: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]


<h3>Practice</h3>


In [ ]:
# Practice: 
# 1. Create a tensor of integers of the size you want
# 2. Convert the previous integer tensor to float tensor
# 3. Convert it to a numpy array



Double-click <b>here</b> for the solution.

<!-- 
your_tensor = torch.tensor([4,2,3,7,1,9])
new_float_tensor = your_tensor.type(torch.FloatTensor)
print(new_float_tensor)
converted_tensor = your_tensor.numpy()
print("Your tensor : ",your_tensor, "\n Converted tensor in numpy array : ", converted_tensor)
-->

<h2 id="Index_Slice">Indexing and Slicing</h2>

In [9]:
X = torch.arange(12)
print("X = ", X)

X =  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


You can access and modify the content of an index:

In [10]:
# Change of the first value
X[0] = 100
print("X = ", X)

X =  tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])


The method <code>item()</code> returns the value of this tensor as a standard Python number. This only works for one element. 

In [11]:
print("The first item of X is given by",X[0].item(),", the first tensor value of X is given by",X[0])

The first item of X is given by 100 , the first tensor value of X is given by tensor(100)


You can slice your tensor such as in numpy :

In [13]:
# Slice of th e 3th to 4th values of the tensor
print(X[2:4])

tensor([2, 3])


<h3>Practice</h3>

In [ ]:
# Practice: 
# 1. Create a tensor whose starting value is 1, ending value 5  and the gap between each pair of adjacent points is 0.5.
# SEE: https://pytorch.org/docs/stable/generated/torch.arange.html
# 2. Slice to the 4th value to the end

Double-click <b>here</b> for the solution.

<!-- 
tensor = torch.arange(1, 5, 0.5)
print(tensor[3:])
-->

<h2 id="Tensor_Func">Tensor Functions</h2>
As well as in numpy, you can use math function in pyTorch. For example: mean(), min(), sin() etc.

In [14]:
math_tensor = torch.tensor([1.0, -1.0, 1, -1])
print("Tensor example: ", math_tensor)
print("Mean: ", math_tensor.mean())
print("Min: ", math_tensor.min())

Tensor example:  tensor([ 1., -1.,  1., -1.])
Mean:  tensor(0.)
Min:  tensor(-1.)


<h1>Torch Tensors in 2D</h1>
<h2 id="Types_Shape">Types and Shape</h2>

<h2>Objective</h2><ul><li> How to perform tensor operations on 2D tensors.</li></ul> 
You can also use <code>torch.tensor()</code> which we used for converting a 1D list to 1D tensor, to convert a 2D list.

In [15]:
# Convert 2D List to 2D Tensor

twoD_list = [[11, 12, 13], 
             [21, 22, 23], 
             [31, 32, 33]]
twoD_tensor = torch.tensor(twoD_list)
print("The 2D list: \n", twoD_list)
print("The New 2D Tensor: \n", twoD_tensor)

The 2D list: 
 [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
The New 2D Tensor: 
 tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


Let us try <code><i>tensor_obj</i>.ndimension()</code> (<code>tensor_obj</code>: This can be any tensor object), <code><i>tensor_obj</i>.shape</code>, and <code><i>tensor_obj</i>.size()</code>

In [16]:
# Try tensor_obj.ndimension(), tensor_obj.shape, tensor_obj.size()

print("The dimension of twoD_tensor: ", twoD_tensor.ndimension())
print("The shape of twoD_tensor: ", twoD_tensor.shape)
print("The shape of twoD_tensor: ", twoD_tensor.size())
print("The number of elements in twoD_tensor: ", twoD_tensor.numel())

The dimension of twoD_tensor:  2
The shape of twoD_tensor:  torch.Size([3, 3])
The shape of twoD_tensor:  torch.Size([3, 3])
The number of elements in twoD_tensor:  9


You can use also all the functions of the first part: <code>.numpy()</code> etc.


Use the  <code><i>.view()<i> </code> method to reshape a tensor. This method receives heavy use, because many neural network components expect their inputs to have a certain shape. Often you will need to reshape before passing your data to the component.

In [17]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns

tensor([[[ 0.4297,  0.4462, -0.2242,  0.9838],
         [ 1.1611, -1.0686, -0.9206, -0.3552],
         [ 0.6997,  0.8456,  0.2159,  1.0449]],

        [[ 0.1783, -1.1267, -1.2097,  1.5483],
         [ 0.0744,  0.6559,  0.6743,  0.8468],
         [-0.0260, -0.2684,  2.0385, -0.3797]]])
tensor([[ 0.4297,  0.4462, -0.2242,  0.9838,  1.1611, -1.0686, -0.9206, -0.3552,
          0.6997,  0.8456,  0.2159,  1.0449],
        [ 0.1783, -1.1267, -1.2097,  1.5483,  0.0744,  0.6559,  0.6743,  0.8468,
         -0.0260, -0.2684,  2.0385, -0.3797]])


<h2 id="Specific matrix">Types and Shape</h2>

In [18]:
# Identity
x = torch.ones(3,2)
print('x =',x,'\n')
# Random floats
x = torch.rand(3, 2)
print('x =',x,'\n')

x = tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 

x = tensor([[0.3356, 0.7179],
        [0.7475, 0.0601],
        [0.8653, 0.0630]]) 



<h2 id="Index_Slice">Indexing and Slicing</h2>


In [19]:
# Use tensor_obj[row, column] OR tensor_obj[row][column] to access certain position

tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1, 2].item())
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1][2].item())

What is the value on 2nd-row 3rd-column?  23
What is the value on 2nd-row 3rd-column?  23


In [20]:
# Use tensor_obj[begin_row_number: end_row_number, begin_column_number: end_column number] 
# and tensor_obj[row][begin_column_number: end_column number] to do the slicing

tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 1st-row first two columns? ", tensor_example[0, 0:2])
print("What is the value on 1st-row first two columns? ", tensor_example[0][0:2])

What is the value on 1st-row first two columns?  tensor([11, 12])
What is the value on 1st-row first two columns?  tensor([11, 12])


In [ ]:
# Practice: 
# Try to change the values on the second column to 0.
# Use slice and index to change the values on the matrix tensor_example.


Double-click <b>here</b> for the solution.

<!--
tensor_example[0:3, 1] = 0
print("The result: ", tensor_example)
-->


<h2 id="Tensor_Op">Tensor Operations</h2> 
<h3>Tensor Addition</h3>


In [ ]:
a = torch.tensor([1, 2])
b = torch.tensor([8, 9])

c = a + b
print('c =', c)


<h3> Scalar Multiplication </h3>


In [ ]:
d = 3 * a
print('a =', a)
print('d = ',d)

<h3>Element-wise Product/Hadamard Product</h3>


In [ ]:
e = a * b
print('a =', a)
print('b = ',b)
print('e = a*b =',e)

<h3>Matrix Multiplication </h3>
We use <code>torch.mm()</code> for calculating the multiplication between tensors with different sizes.


In [ ]:
# Calculate [[0, 1, 1], [1, 0, 1]] * [[1, 1], [1, 1], [-1, 1]]

A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)
print("The result of A * B: ", A_times_B)

<h3>Practice</h3>
Try to create your own two tensors (<code>X</code> and <code>Y</code>) with different sizes, and multiply them.


In [ ]:
# Practice: Calculate the product of two tensors (X and Y) with different sizes such as below

# Type your code here


Double-click <b>here</b> for the solution.

<!--
X = torch.tensor([[0, 1], [1, 2]])
Y = torch.tensor([[-1, -2, 0], [2, 1, 2]])
X_times_Y = torch.mm(X, Y)
print("The result of X * Y: ", X_times_Y)
-->